---
- import_tasks: Ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: Run Arch Tasks
  ansible.builtin.import_tasks: Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: "swaylock | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/swaylock"
    state: directory

- name: "swaylock | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files/swaylock"
    dest: "{{ ansible_user_dir }}/.config/swaylock"
    state: link
    force: true