---
- name: DotFiles Config
  hosts: localhost
  connection: local
  gather_facts: true  # Ensure facts are gathered to use Ansible's default OS facts as well

  pre_tasks:
    - name: Detect WSL, Windows, and Ubuntu
      ansible.builtin.import_tasks: pre_tasks/detect_wsl.yml
      tags:
        - always

    - name: Detect wsl variable
      ansible.builtin.debug:
        var: ansible_host_environment_is_wsl
      tags:
        - always

    - name: Confirm PowerShell Execution Policy
      ansible.builtin.import_tasks: pre_tasks/powershell_executionpolicy.yml
      when: ansible_host_environment_is_wsl or ansible_host_environment_is_windows
      tags:
        - always

    - name: Detect Host User
      ansible.builtin.import_tasks: pre_tasks/whoami.yml
      tags:
        - always

  tasks:
    - name: Set roles 
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) }}"
      tags:
        - always

    - name: Display roles and environment info
      ansible.builtin.debug:
        msg: "Running on WSL: {{ ansible_host_environment_is_wsl }}, Windows: {{ ansible_host_environment_is_windows }}, Ubuntu: {{ ansible_host_environment_is_ubuntu }}, OS Family: {{ ansible_os_family }} | Roles: {{ run_roles }}"
      tags:
        - always

    - name: Run roles (only if not NixOS)
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      when: ansible_os_family != "NixOS"  # Exclude NixOS
      tags:
        - always
        
    - name: Execute NixOS flake script
      ansible.builtin.command: >
        ./install.sh
      args:
        chdir: /nixos-config  # Replace with the path to your NixOS folder
      when: ansible_os_family == "NixOS"
      tags:
        - always
