---
- name: Hypr Monitors | Ubuntu | Install runtime packages
  ansible.builtin.apt:
    name:
      - python3-pyside6.qtcore
      - python3-pyside6.qtgui
      - python3-pyside6.qtqml
      - python3-pyside6.qtquick
      - python3-pyside6.qtquickcontrols2
      - qml6-module-qtquick
      - qml6-module-qtquick-controls
      - qml6-module-qtquick-layouts
    state: present
    update_cache: true
  become: true
