---
- name: "Nala | Detecting Installed Nala"
  ansible.builtin.command:
    cmd: which nala
  changed_when: false
  register: nala_cmd
  failed_when: false

- name: "Nala | Register nala status installed"
  ansible.builtin.set_fact:
    nala_is_installed: true
  when: nala_cmd.stdout|length > 0

- name: "Nala | Register nala status not installed"
  ansible.builtin.set_fact:
    nala_is_installed: false
  when: nala_cmd.stdout|length == 0

# - name: "Nala | Install Nala APT Repo"
#   block:
#     - name: "Nala | Create trusted.gpg.d directory"
#       ansible.builtin.file:
#         path: /etc/apt/trusted.gpg.d
#         state: directory
#         mode: '0755'
#       become: true
#     - name: "Nala | Add nala repo gpg key"
#       ansible.builtin.shell: |
#         curl -fsSL https://deb.volian.org/volian/dists/scar/Release.gpg | gpg --dearmor -o /etc/apt/trusted.gpg.d/volian-archive-scar-unstable.gpg
#       args:
#         creates: /etc/apt/trusted.gpg.d/volian-archive-scar-unstable.gpg
#       become: true
#     - name: "Nala | Add nala repository source"
#       apt_repository:
#         repo: "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/volian-archive-scar-unstable.gpg] http://deb.volian.org/volian/ scar main"
#         state: present
#   become: true
#   when: not nala_is_installed

- name: "Nala | Install Nala"
  ansible.builtin.apt:
    name: nala
    state: present
  become: true
  when: ansible_distribution_major_version == "22"

- name: "Nala | Install Nala-legacy"
  apt:
    name: nala-legacy
    state: present
    update_cache: true
  become: true
  when: ansible_distribution_major_version == "20"