---
- name: Run Ubuntu Tasks
  ansible.builtin.include_tasks: Ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: Run Darwin Tasks
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/MacOSX.yml"
  register: vscode_darwin_config
  when: ansible_os_family == 'Darwin'

- name: Include Darwin Tasks
  ansible.builtin.include_tasks: MacOSX.yml
  when:
    - ansible_os_family == 'Darwin'
    - vscode_darwin_config.stat.exists
