---
- name: K8s | Ensure required packages are installed
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
    state: present
  become: true

- name: K8s | Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

- name: K8s | Download Kubernetes signing key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    mode: '0644'
    force: yes
  become: true

- name: K8s | Add Kubernetes apt repository
  ansible.builtin.command:
    cmd: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: Set permissions for the repository list file
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/kubernetes.list
    mode: '0644'
  become: true

- name: Debug repository list file
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/kubernetes.list
  become: true
  register: repo_list_file

- name: Print repository list file details
  ansible.builtin.debug:
    var: repo_list_file

- name: K8s | Update apt package index
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: K8s | Install kubectl
  ansible.builtin.apt:
    name: kubectl
    state: present
  become: true
