---
- name: K8s | Ensure required packages are installed
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
  become: true

- name: K8s | Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

- name: K8s | Add Kubernetes apt key and repository
  ansible.builtin.shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list
  become: true
  force: true

- name: K8s | Update apt package index
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: K8s | Install kubectl
  ansible.builtin.apt:
    name: kubectl
    state: present
  become: true
