---
- name: K8s | Ensure required packages are installed
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
    state: present
  become: true

- name: K8s | Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

- name: K8s | Download and add Kubernetes signing key
  ansible.builtin.command:
    cmd: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  become: true

- name: K8s | Set permissions for the keyring
  ansible.builtin.file:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    mode: '0644'
  become: true

- name: K8s | Add Kubernetes apt repository
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /'
    state: present
  become: true
  register: repo_result

- name: Debug repo addition
  ansible.builtin.debug:
    var: repo_result

- name: K8s | Update apt package index
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: K8s | Install kubectl
  ansible.builtin.apt:
    name: kubectl
    state: present
  become: true
