---

- name: "EduVPN | Update apt cache"
  ansible.builtin.apt:
    update_cache: true
  become: true


- name: "EduVPN | Install dependencies"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - apt-transport-https
    - wget
    - gnupg

- name: "EduVPN | Ensure keyring directory exists"
  ansible.builtin.file:
    path: /usr/share/keyrings
    state: directory
    mode: "0755"
  become: true

- name: "EduVPN | Download and Add EduVPN Key"
  ansible.builtin.shell: |
    wget -O- https://app.eduvpn.org/linux/v4/deb/app+linux@eduvpn.org.asc | gpg --dearmor | sudo tee /usr/share/keyrings/eduvpn-v4.gpg >/dev/null
  args:
    creates: /usr/share/keyrings/eduvpn-v4.gpg

- name: "EduVPN | Add EduVPN Repository"
  ansible.builtin.shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/eduvpn-v4.gpg] https://app.eduvpn.org/linux/v4/deb/ focal main" | sudo tee /etc/apt/sources.list.d/eduvpn-v4.list
  args:
    creates: /etc/apt/sources.list.d/eduvpn-v4.list

- name: "EduVPN | Update apt cache"
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: "EduVPN | Install eduvpn-client"
  ansible.builtin.apt:
    name: eduvpn-client
    state: present
  become: true
