- name: Set Logseq variables
  ansible.builtin.set_fact:
    logseq_version: "0.11.0"
    logseq_install_dir: "/opt/logseq"
    logseq_bin_dir: "/usr/local/bin"
    logseq_desktop_dir: "/usr/share/applications"
    logseq_icon_dir: "/usr/share/icons/hicolor/256x256/apps"
    logseq_temp_dir: "/tmp/logseq-install"

- name: Create temporary directory
  ansible.builtin.file:
    path: "{{ logseq_temp_dir }}"
    state: directory
    mode: '0755'
  become: true

- name: Ensure Git LFS files are pulled
  ansible.builtin.command: git lfs pull
  delegate_to: localhost
  run_once: true
  become: false

- name: Copy Logseq zip file from role files
  ansible.builtin.copy:
    src: "logseq-linux-x64-builds.zip"
    dest: "{{ logseq_temp_dir }}/logseq-linux-x64-builds.zip"
    mode: '0644'
  become: true

- name: Extract outer zip file
  ansible.builtin.unarchive:
    src: "{{ logseq_temp_dir }}/logseq-linux-x64-builds.zip"
    dest: "{{ logseq_temp_dir }}"
    remote_src: yes
  become: true

- name: Extract inner Logseq zip file
  ansible.builtin.unarchive:
    src: "{{ logseq_temp_dir }}/Logseq-linux-x64-{{ logseq_version }}.zip"
    dest: "{{ logseq_temp_dir }}"
    remote_src: yes
  become: true

- name: Create Logseq installation directory
  ansible.builtin.file:
    path: "{{ logseq_install_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Copy Logseq files to installation directory
  ansible.builtin.copy:
    src: "{{ logseq_temp_dir }}/Logseq-linux-x64/"
    dest: "{{ logseq_install_dir }}/"
    owner: root
    group: root
    mode: preserve
    remote_src: yes
  become: true

- name: Make Logseq binary executable
  ansible.builtin.file:
    path: "{{ logseq_install_dir }}/Logseq"
    mode: '0755'
  become: true

- name: Fix permissions for all executables in Logseq directory
  ansible.builtin.shell: |
    find {{ logseq_install_dir }} -type f -name "*.so*" -exec chmod 755 {} \;
    find {{ logseq_install_dir }} -type f -name "Logseq" -exec chmod 755 {} \;
    find {{ logseq_install_dir }} -type f -name "chrome-sandbox" -exec chmod 4755 {} \;
    find {{ logseq_install_dir }} -type f -executable -exec chmod 755 {} \;
    chmod 755 {{ logseq_install_dir }}
  become: true
  ignore_errors: true

- name: Create symbolic link in PATH
  ansible.builtin.copy:
    dest: "{{ logseq_bin_dir }}/logseq"
    content: |
      #!/bin/bash
      exec {{ logseq_install_dir }}/Logseq --no-sandbox "$@"
    mode: '0755'
  become: true

- name: Create desktop entry
  ansible.builtin.copy:
    dest: "{{ logseq_desktop_dir }}/logseq.desktop"
    content: |
      [Desktop Entry]
      Name=Logseq
      Comment=A privacy-first, open-source platform for knowledge management and collaboration
      Exec={{ logseq_install_dir }}/Logseq --no-sandbox %U
      Terminal=false
      Type=Application
      Icon=logseq
      Categories=Office;TextEditor;
      MimeType=x-scheme-handler/logseq;
      StartupNotify=true
      StartupWMClass=Logseq
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Download and install Logseq icon
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/logseq/logseq/master/resources/icon.png"
    dest: "{{ logseq_icon_dir }}/logseq.png"
    mode: '0644'
  become: true
  ignore_errors: true

- name: Update desktop database
  ansible.builtin.command: update-desktop-database {{ logseq_desktop_dir }}
  become: true
  ignore_errors: true

- name: Set proper permissions for chrome-sandbox
  ansible.builtin.file:
    path: "{{ logseq_install_dir }}/chrome-sandbox"
    mode: '4755'
    owner: root
    group: root
  become: true

# New tasks for symlink and git repository setup
- name: Create Logseq directories in user home
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0755'
  loop:
    - "{{ ansible_user_dir }}/.logseq"
    - "{{ ansible_user_dir }}/logseq"
    - "{{ ansible_user_dir }}/logseq/graphs"
  become: false

- name: Create symlink from files/dot-logseq to ~/.logseq
  ansible.builtin.file:
    src: "{{ role_path }}/files/dot-logseq"
    dest: "{{ ansible_user_dir }}/.logseq"
    state: link
    force: yes
  become: false

- name: Clone valiantlynx_logseq repository
  ansible.builtin.git:
    repo: "git@github.com:valiantlynx/sqlite_valiantlynx_logseq.git"
    dest: "{{ ansible_user_dir }}/logseq/graphs/sqlite_valiantlynx_logseq"
    version: main
    force: yes
  become: false

- name: Set proper ownership for cloned repository
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/logseq/graphs/sqlite_valiantlynx_logseq"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    recurse: yes
  become: false

- name: Clean up temporary files
  ansible.builtin.file:
    path: "{{ logseq_temp_dir }}"
    state: absent
  become: true
