---
- name: "SSH | Copy SSH keys"
  copy:
    dest: "{{ ansible_user_dir | default(ansible_env.HOME) }}/.ssh/{{ ssh_key_item.key }}"
    content: "{{ ssh_key_item.value }}"
    mode: 0600
  no_log: true
  loop_control:
    loop_var: ssh_key_item
  with_items: "{{ ssh_key | default({}) | dict2items }}"

# - name: Copy config
#   ansible.builtin.template:
#     dest: "{{ ansible_user_dir | default(ansible_env.HOME) }}/.ssh/config"
#     src: "config.j2"

- name: Check if dotfiles directory exists
  stat:
    path: "{{ ansible_user_dir }}/.dotfiles"
  register: dotfiles_dir

- name: Change Git remote from HTTPS to SSH
  command: git remote set-url origin git@github.com:valiantlynx/dotfiles.git
  args:
    chdir: "{{ ansible_user_dir }}/.dotfiles"
  when: dotfiles_dir.stat.exists and dotfiles_dir.stat.isdir
