---
- name: "System | Update APT Repos and Upgrade APT Packages"
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
    state: latest
    autoremove: true
    autoclean: true
  become: true

- name: "System | Install"
  ansible.builtin.apt:
    name:
      - jq
      - open-iscsi
      - unzip
      - fuse 
      - libfuse2
    state: present
  become: true

