---
- name: "FZF | Uninstall APT fzf"
  ansible.builtin.apt:
    name: fzf
    state: absent
  become: true

- name: "FZF | Clone Latest Version"
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    depth: 1
    dest: "{{ ansible_user_dir | default(ansible_env.HOME) }}/.fzf"
  notify: "Install FZF"
