---
- name: Run Ubuntu Tasks
  ansible.builtin.include_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: Run Arch Tasks
  ansible.builtin.include_tasks: Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: Run Darwin Tasks
  ansible.builtin.include_tasks: Darwin.yml
  when: ansible_os_family == 'Darwin'
