---
- import_tasks: Ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: Run Arch Tasks
  ansible.builtin.import_tasks: Archlinux.yml
  when: ansible_os_family == 'Archlinux'


- name: "waypaper | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/waypaper"
    state: directory

- name: "waypaper | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files/waypaper"
    dest: "{{ ansible_user_dir }}/.config/waypaper"
    state: link
    force: true