---
- name: Terraform | Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Terraform | Add HashiCorp GPG key
  ansible.builtin.shell: |
    curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /etc/apt/keyrings/hashicorp-archive-keyring.gpg
  args:
    creates: /etc/apt/keyrings/hashicorp-archive-keyring.gpg
  become: true

- name: Terraform | Add HashiCorp repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release | lower }} main"
    state: present
    filename: hashicorp
  become: true

- name: Terraform | Install Terraform
  apt:
    name: terraform
    state: present
  become: true