---
- name: "tmux | Install TPM"
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
  when: ansible_os_family != "NixOS"  # Exclude NixOS

- name: "tmux | Configure tmux"
  ansible.builtin.copy:
    src: tmux
    dest: "{{ ansible_user_dir }}/.config/"
    mode: 0644
    directory_mode: 0755
    force: true
