---
- import_tasks: Ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: Run Arch Tasks
  ansible.builtin.import_tasks: Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: "tmux | Install TPM"
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: "tmux | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/tmux"
    state: directory

- name: "Tmux | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files/tmux"
    dest: "{{ ansible_user_dir }}/.config/tmux"
    state: link
    force: true