---
- name: "Vivaldi | Set target version"
  ansible.builtin.set_fact:
    vivaldi_target_version: "7.5.3735.44"

- name: "Vivaldi | Getting current version information"
  ansible.builtin.command:
    cmd: dpkg-query -W -f='${Version}' vivaldi-stable
  register: current_vivaldi_version
  changed_when: false
  failed_when: false

- name: "Vivaldi | Extract current version"
  ansible.builtin.set_fact:
    current_vivaldi_version: "{{ current_vivaldi_version.stdout | default('0.0.0') }}"

- name: "Vivaldi | Show current version debug"
  ansible.builtin.debug:
    var: current_vivaldi_version

- name: "Vivaldi | Show target version debug"
  ansible.builtin.debug:
    var: vivaldi_target_version

- name: "Vivaldi | Install"
  when: vivaldi_target_version not in current_vivaldi_version|default('0.0.0')
  block:
    - name: "Vivaldi | Define architecture"
      ansible.builtin.set_fact:
        vivaldiarch: "{{ ansible_machine | replace('x86_64', 'amd64') | replace('aarch64', 'arm64') }}"

    - name: "Vivaldi | Define filename"
      ansible.builtin.set_fact:
        vivaldi_filename: "vivaldi-stable_{{ vivaldi_target_version }}-1_{{ vivaldiarch }}.deb"

    - name: "Vivaldi | Ensure clean download destination"
      ansible.builtin.file:
        path: "/tmp/{{ vivaldi_filename }}"
        state: absent
      become: true

    - name: "Vivaldi | Download Vivaldi"
      ansible.builtin.get_url:
        url: "https://downloads.vivaldi.com/stable/{{ vivaldi_filename }}"
        dest: "/tmp/{{ vivaldi_filename }}"
        mode: "0644"
        force: true
      notify:
        - Cleanup Vivaldi downloaded deb

    - name: "Vivaldi | Install Vivaldi"
      ansible.builtin.apt:
        deb: "/tmp/{{ vivaldi_filename }}"
        state: present
        update_cache: true
      become: true
      notify:
        - Cleanup Vivaldi downloaded deb
