---
- name: "waybar | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/waybar"
    state: directory

- name: "Waybar | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files/waybar"
    dest: "{{ ansible_user_dir }}/.config/waybar"
    state: link
    force: true