---
- name: Remove tarball
  ansible.builtin.file:
    path: "/tmp/asciiquarium.tar.gz"
    state: absent
  become: true

- name: Remove extracted tarball
  ansible.builtin.file:
    path: /tmp/asciiquarium
    state: absent
  become: true
