# Matugen-generated Hyprlock colors
$base      = rgb(19120c)
$mantle    = rgb(251e17)
$crust     = rgb(130d07)
$text      = rgb(eee0d5)
$subtext0  = rgb(d5c3b5)
$surface0  = rgb(50453a)
$mauve     = rgb(fbba73)
$green     = rgb(becc9b)
$red       = rgb(ffb4ab)
$peach     = rgb(e1c1a3)
$base_alpha85   = rgba(19120cD9)
$mantle_alpha60 = rgba(251e1799)
$mauve_alpha30  = rgba(fbba734D)
