# Matugen-generated Hyprlock colors
$base      = rgb(0e1514)
$mantle    = rgb(1a2121)
$crust     = rgb(090f0f)
$text      = rgb(dde4e3)
$subtext0  = rgb(bec8c8)
$surface0  = rgb(3f4948)
$mauve     = rgb(80d4d5)
$green     = rgb(b3c8e9)
$red       = rgb(ffb4ab)
$peach     = rgb(b0cccb)
$base_alpha85   = rgba(0e1514D9)
$mantle_alpha60 = rgba(1a212199)
$mauve_alpha30  = rgba(80d4d54D)
