# Matugen-generated Hyprlock colors
$base      = rgb(101417)
$mantle    = rgb(1c2024)
$crust     = rgb(0b0f12)
$text      = rgb(e0e3e8)
$subtext0  = rgb(c1c7ce)
$surface0  = rgb(41474d)
$mauve     = rgb(96cdf8)
$green     = rgb(cfc0e8)
$red       = rgb(ffb4ab)
$peach     = rgb(b7c9d9)
$base_alpha85   = rgba(101417D9)
$mantle_alpha60 = rgba(1c202499)
$mauve_alpha30  = rgba(96cdf84D)
