---
- name: Detect WSL
  ansible.builtin.shell: |
    if [[ $(grep -i microsoft /proc/version) ]] || [[ $(grep -i wsl /proc/version) ]]; then
      if [ -n "$WSL_DISTRO_NAME" ] || [ -n "$WSLENV" ]; then
        echo true
      else
        echo false
      fi
    else
      echo false
    fi
  register: wsl_detection_result
  args:
    executable: /bin/bash
  ignore_errors: true
  changed_when: false

- name: Register WSL State fact
  ansible.builtin.set_fact:
    ansible_host_environment_is_wsl: "{{ wsl_detection_result.stdout == 'true' }}"

- name: Detect Native Windows
  ansible.builtin.shell:
    cmd: Test-Path C:\Windows\System32
    executable: powershell.exe
  register: windows_detection_result
  ignore_errors: true
  changed_when: false

- name: Register Native Windows State fact
  ansible.builtin.set_fact:
    ansible_host_environment_is_windows: "{{ windows_detection_result.rc == 0 and not ansible_host_environment_is_wsl }}"

- name: Detect Ubuntu OS
  ansible.builtin.shell: |
    if [[ $(grep -i ubuntu /etc/os-release) ]]; then
      echo true
    else
      echo false
    fi
  register: ubuntu_detection_result
  changed_when: false
  failed_when: false
  args:
    executable: /bin/bash

- name: Register Ubuntu State fact
  ansible.builtin.set_fact:
    ansible_host_environment_is_ubuntu: "{{ ubuntu_detection_result.stdout == 'true' }}"

- name: Get facts about the current container
  community.docker.current_container_facts:

- name: Print detected container ID
  ansible.builtin.debug:
    msg: "Running in container with ID {{ ansible_module_container_id }}"
  when: ansible_module_running_in_container

- name: Print container type
  ansible.builtin.debug:
    msg: "Container environment detected: {{ ansible_module_container_type }}"
  when: ansible_module_running_in_container

- name: Print if not running in a container
  ansible.builtin.debug:
    msg: "Not running inside a container"
  when: not ansible_module_running_in_container
