---
- name: Detect WSL
  ansible.builtin.shell: |
    if [[ $(grep -i microsoft /proc/version) ]] || [[ $(grep -i wsl /proc/version) ]]; then
      if [ -n "$WSL_DISTRO_NAME" ] || [ -n "$WSLENV" ]; then
        echo true
      else
        echo false
      fi
    else
      echo false
    fi
  register: wsl_detection_result
  args:
    executable: /bin/bash
  ignore_errors: true
  changed_when: false

- name: Register WSL State fact
  ansible.builtin.set_fact:
    ansible_host_environment_is_wsl: "{{ wsl_detection_result.stdout == 'true' }}"

- name: Detect Native Windows
  ansible.builtin.shell:
    cmd: Test-Path C:\Windows\System32
    executable: powershell.exe
  register: windows_detection_result
  ignore_errors: true
  changed_when: false

- name: Register Native Windows State fact
  ansible.builtin.set_fact:
    ansible_host_environment_is_windows: "{{ windows_detection_result.rc == 0 and not ansible_host_environment_is_wsl }}"

- name: Detect Ubuntu OS
  ansible.builtin.shell: |
    if [[ $(grep -i ubuntu /etc/os-release) ]]; then
      echo true
    else
      echo false
    fi
  register: ubuntu_detection_result
  changed_when: false
  failed_when: false
  args:
    executable: /bin/bash

- name: Register Ubuntu State fact
  ansible.builtin.set_fact:
    ansible_host_environment_is_ubuntu: "{{ ubuntu_detection_result.stdout == 'true' }}"

- name: Detect Docker
  ansible.builtin.shell: |
    if [ -f /.dockerenv ]; then
      echo true
    else
      echo false
    fi
  register: docker_detection_result
  args:
    executable: /bin/bash
  ignore_errors: true
  changed_when: false

- name: Register Docker State fact
  ansible.builtin.set_fact:
    ansible_host_environment_is_docker: "{{ docker_detection_result.stdout == 'true' }}"
