- name: Check Current PowerShell Execution Policy
  ansible.builtin.shell:
    cmd: Get-ExecutionPolicy
    executable: powershell.exe
  register: current_policy
  failed_when: current_policy.rc != 0
  changed_when: false

- name: Set PowerShell Execution Policy if not already set
  ansible.builtin.shell:
    cmd: Set-ExecutionPolicy RemoteSigned -Force -Scope CurrentUser
    executable: powershell.exe
  when: "'RemoteSigned' not in current_policy.stdout"
