---
- name: "Unity Hub | Install dependencies"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - apt-transport-https
    - wget
    - gnupg

- name: "Unity Hub | Ensure keyring directory exists"
  ansible.builtin.file:
    path: /usr/share/keyrings
    state: directory
    mode: "0755"
  become: true

- name: "Unity Hub | Download and Add Unity Hub Key"
  ansible.builtin.shell: |
    wget -qO - https://hub.unity3d.com/linux/keys/public | gpg --dearmor > /usr/share/keyrings/Unity_Technologies_ApS.gpg
  args:
    creates: /usr/share/keyrings/Unity_Technologies_ApS.gpg
  become: true

- name: "Unity Hub | Add Unity Hub Repository"
  ansible.builtin.shell: |
    echo "deb [signed-by=/usr/share/keyrings/Unity_Technologies_ApS.gpg] https://hub.unity3d.com/linux/repos/deb stable main" > /etc/apt/sources.list.d/unityhub.list
  args:
    creates: /etc/apt/sources.list.d/unityhub.list
  become: true

- name: "Unity Hub | Update apt cache"
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: "Unity Hub | Install Unity Hub"
  ansible.builtin.apt:
    name: unityhub
    state: present
  become: true
