- name: "Neovim | Ubuntu | Dependencies"
  ansible.builtin.apt:
    name:
      - cmake
      - curl
      - pkg-config
      - libtool
      - unzip
      - ansible-lint
      - ripgrep
    state: present
  become: true

- name: "Neovim | Ubuntu | Install"
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present
  become: true
  ignore_errors: true

- name: "Neovim | Ubuntu | Install"
  ansible.builtin.apt:
    name: neovim
    state: present
  become: true
